[package]
name = "blazing_rust_brief"
version = "0.1.0"
authors = ["Galudisu <galudisu@gmail.com>"]
edition = "2018"

license = "MIT/Apache-2.0"
readme = "README.MD"

[dependencies]
blazing_rust_brief_derive = { version = "0.1.0", path = "../blazing_rust_brief_derive" }
