[package]
name = "blazing_rust_piston"
version = "0.1.0"
authors = ["Galudisu <galudisu@gmail.com>"]
edition = "2018"

license = "MIT/Apache-2.0"
readme = "README.MD"

[dependencies]
piston_window = "0.81.0"
